steps:
  # Step 1: Build the Docker image using Google Container Registry (gcr.io)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg=API_KEY=${_API_KEY}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/matkulscribe'
      - '.'

  # Step 2: Push the built image to the container registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/matkulscribe'

  # Step 3: Deploy the image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'matkulscribe'
      - '--image=gcr.io/$PROJECT_ID/matkulscribe'
      - '--region=asia-southeast2'
      - '--port=80'
      - '--platform=managed'
      - '--allow-unauthenticated'

# Specify the output images to be registered in Google Cloud Build artifacts
images:
  - 'gcr.io/$PROJECT_ID/matkulscribe'

# Define flexible substitution parameters that can be overridden at trigger run time
substitutions:
  _API_KEY: 'AIzaSyAFGYqFpuR_7m-Q_BEcr89VWbz1c2KKs_s' # Pass this securely during build execution

options:
  logging: CLOUD_LOGGING_ONLY
